document.getElementById("myDonat-sidebar").onclick=function(){window.open("https://sobe.ru/na/qa","_blank")};document.getElementById("myDream-sidebar").onclick=function(){window.open("https://sobe.ru/na/na_me4tu_noutbuk_vmsi","_blank")};document.getElementById("myQuestion-sidebar").onclick=function(){window.open("https://sobe.ru/na/vopros_q12x","_blank")};document.getElementById("Book-Ричард").onclick=function(){window.open("https://eksmo.ru/series/ballady-o-richarde-dlinnye-ruki-ID487/","_blank")};
document.getElementById("Book-C").onclick=function(){window.open("https://www.labirint.ru/books/512950/","_blank")};document.getElementById("Book-Тоненбаума").onclick=function(){window.open("https://www.labirint.ru/search/%D0%AD%D0%BD%D0%B4%D1%80%D1%8E%20%D0%A2%D0%B0%D0%BD%D0%B5%D0%BD%D0%B1%D0%B0%D1%83%D0%BC/?stype=0&available=1&wait=1&preorder=1&paperbooks=1","_blank")};document.getElementById("Donat-footer-d").onclick=function(){window.open("https://sobe.ru/na/qa","_blank")};
document.getElementById("Dream-footer-d").onclick=function(){window.open("https://sobe.ru/na/na_me4tu_noutbuk_vmsi","_blank")};document.getElementById("Question-footer-d").onclick=function(){window.open("https://sobe.ru/na/vopros_q12x","_blank")};document.getElementById("Telegram-footer-d").onclick=function(){window.open("https://msngr.link/tg/malloc_ru","_blank")};
document.getElementById("Youtube-footer-d").onclick=function(){window.open("https://www.youtube.com/channel/UCIAboMgPOBcFR9Y5GoUdoTw","_blank")};document.getElementById("Topmail-footer-d").onclick=function(){window.open("https://top.mail.ru/jump?from=3211268","_blank")};document.getElementById("Payeer-footer-d").onclick=function(){window.open("https://payeer.com/04184305","_blank")};document.getElementById("Donat-footer-m").onclick=function(){window.open("https://sobe.ru/na/qa","_blank")};
document.getElementById("Dream-footer-m").onclick=function(){window.open("https://sobe.ru/na/na_me4tu_noutbuk_vmsi","_blank")};document.getElementById("Question-footer-m").onclick=function(){window.open("https://sobe.ru/na/vopros_q12x","_blank")};document.getElementById("Telegram-footer-m").onclick=function(){window.open("https://msngr.link/tg/malloc_ru","_blank")};
document.getElementById("Youtube-footer-m").onclick=function(){window.open("https://www.youtube.com/channel/UCIAboMgPOBcFR9Y5GoUdoTw","_blank")};document.getElementById("Topmail-footer-m").onclick=function(){window.open("https://top.mail.ru/jump?from=3211268","_blank")};document.getElementById("Payeer-footer-m").onclick=function(){window.open("https://payeer.com/04184305","_blank")};var mySidebar=document.getElementById("mySidebar"),overlayBg=document.getElementById("myOverlay");
function malloc_open(){"block"===mySidebar.style.display?(mySidebar.style.display="none",overlayBg.style.display="none"):(mySidebar.style.display="block",overlayBg.style.display="block")}function malloc_close(){mySidebar.style.display="none";overlayBg.style.display="none"}
function date(){var a=new Date;return" "+"Воскресенье Понедельник Вторник Среда Четверг Пятница Суббота".split(" ")[a.getDay()]+" "+a.getDate()+" "+"января февраля марта апреля мая июня июля августа сентября октября ноября декабря".split(" ")[a.getMonth()]+" "+a.getFullYear()+" "}setInterval(function(){document.getElementById("mydate").innerHTML=date()},0);function zero_first_format(a){10>a&&(a="0"+a);return a}
function time(){var a=new Date,d=zero_first_format(a.getHours()),b=zero_first_format(a.getMinutes());a=zero_first_format(a.getSeconds());return" "+d+":"+b+":"+a+" "}setInterval(function(){document.getElementById("mytime").innerHTML=time()});var _tmr=window._tmr||(window._tmr=[]);_tmr.push({id:"3211268",type:"pageView",start:(new Date).getTime()});
(function(a,d,b){if(!a.getElementById(b)){var c=a.createElement("script");c.type="text/javascript";c.async=!0;c.id=b;c.src="https://top-fwz1.mail.ru/js/code.js";b=function(){var b=a.getElementsByTagName("script")[0];b.parentNode.insertBefore(c,b)};"[object Opera]"==d.opera?a.addEventListener("DOMContentLoaded",b,!1):b()}})(document,window,"topmailru-code");
