document.getElementById("link-article-1").onclick=function(){window.open("content/1-kak-obnovit'-ubuntu-cherez-terminal.html","_self")};document.getElementById("link-article-2").onclick=function(){window.open("content/2-kak-otpravit'-sushchestvuyushchiy-proekt-na-github.html","_self")};document.getElementById("link-article-3").onclick=function(){window.open("content/3-linux-rabota-s-katalogami-i-faylami-chast'-pervaya.html","_self")};
document.getElementById("link-article-4").onclick=function(){window.open("content/4-linux-rabota-s-katalogami-i-faylami-chast'-vtoraya.html","_self")};document.getElementById("link-article-5").onclick=function(){window.open("content/5-hello-world-na-si.html","_self")};document.getElementById("link-article-6").onclick=function(){window.open("content/6-converter-valyut-na-si.html","_self")};
document.getElementById("link-article-7").onclick=function(){window.open("content/7-otzhimaniya-v-otkaz-programma.html","_self")};document.getElementById("link-article-8").onclick=function(){window.open("content/8-tri-zolotykh-uprazhneniya-programma.html","_self")};document.getElementById("link-article-9").onclick=function(){window.open("content/9-raspredeleniye-maksimal'nogo-kolichestva-povtoreniy-na-podkhody.html","_self")};
document.getElementById("link-article-10").onclick=function(){window.open("content/10-yedinorog.html","_self")};document.getElementById("sidebar-link-article-1").onclick=function(){window.open("content/1-kak-obnovit'-ubuntu-cherez-terminal.html","_self")};document.getElementById("sidebar-link-article-2").onclick=function(){window.open("content/2-kak-otpravit'-sushchestvuyushchiy-proekt-na-github.html","_self")};
document.getElementById("sidebar-link-article-3").onclick=function(){window.open("content/3-linux-rabota-s-katalogami-i-faylami-chast'-pervaya.html","_self")};document.getElementById("sidebar-link-article-4").onclick=function(){window.open("content/4-linux-rabota-s-katalogami-i-faylami-chast'-vtoraya.html","_self")};document.getElementById("sidebar-link-article-5").onclick=function(){window.open("content/5-hello-world-na-si.html","_self")};
document.getElementById("sidebar-link-article-6").onclick=function(){window.open("content/6-converter-valyut-na-si.html","_self")};document.getElementById("sidebar-link-article-7").onclick=function(){window.open("content/7-otzhimaniya-v-otkaz-programma.html","_self")};document.getElementById("sidebar-link-article-8").onclick=function(){window.open("content/8-tri-zolotykh-uprazhneniya-programma.html","_self")};
document.getElementById("sidebar-link-article-9").onclick=function(){window.open("content/9-raspredeleniye-maksimal'nogo-kolichestva-povtoreniy-na-podkhody.html","_self")};document.getElementById("sidebar-link-article-10").onclick=function(){window.open("content/10-yedinorog.html","_self")};document.getElementById("Donat-footer-d").onclick=function(){window.open("https://sobe.ru/na/qa","_blank")};
document.getElementById("Dream-footer-d").onclick=function(){window.open("https://sobe.ru/na/na_me4tu_noutbuk_vmsi","_blank")};document.getElementById("Question-footer-d").onclick=function(){window.open("https://sobe.ru/na/vopros_q12x","_blank")};document.getElementById("Telegram-footer-d").onclick=function(){window.open("https://msngr.link/tg/malloc_ru","_blank")};
document.getElementById("Youtube-footer-d").onclick=function(){window.open("https://www.youtube.com/channel/UCIAboMgPOBcFR9Y5GoUdoTw","_blank")};document.getElementById("Topmail-footer-d").onclick=function(){window.open("https://top.mail.ru/jump?from=3211268","_blank")};document.getElementById("Payeer-footer-d").onclick=function(){window.open("https://payeer.com/04184305","_blank")};document.getElementById("Donat-footer-m").onclick=function(){window.open("https://sobe.ru/na/qa","_blank")};
document.getElementById("Dream-footer-m").onclick=function(){window.open("https://sobe.ru/na/na_me4tu_noutbuk_vmsi","_blank")};document.getElementById("Question-footer-m").onclick=function(){window.open("https://sobe.ru/na/vopros_q12x","_blank")};document.getElementById("Telegram-footer-m").onclick=function(){window.open("https://msngr.link/tg/malloc_ru","_blank")};
document.getElementById("Youtube-footer-m").onclick=function(){window.open("https://www.youtube.com/channel/UCIAboMgPOBcFR9Y5GoUdoTw","_blank")};document.getElementById("Topmail-footer-m").onclick=function(){window.open("https://top.mail.ru/jump?from=3211268","_blank")};document.getElementById("Payeer-footer-m").onclick=function(){window.open("https://payeer.com/04184305","_blank")};var mySidebar=document.getElementById("mySidebar"),overlayBg=document.getElementById("myOverlay");
function malloc_open(){"block"===mySidebar.style.display?(mySidebar.style.display="none",overlayBg.style.display="none"):(mySidebar.style.display="block",overlayBg.style.display="block")}function malloc_close(){mySidebar.style.display="none";overlayBg.style.display="none"}
function date(){var a=new Date;return" "+"Воскресенье Понедельник Вторник Среда Четверг Пятница Суббота".split(" ")[a.getDay()]+" "+a.getDate()+" "+"января февраля марта апреля мая июня июля августа сентября октября ноября декабря".split(" ")[a.getMonth()]+" "+a.getFullYear()+" "}setInterval(function(){document.getElementById("mydate").innerHTML=date()},0);function zero_first_format(a){10>a&&(a="0"+a);return a}
function time(){var a=new Date,d=zero_first_format(a.getHours()),b=zero_first_format(a.getMinutes());a=zero_first_format(a.getSeconds());return" "+d+":"+b+":"+a+" "}setInterval(function(){document.getElementById("mytime").innerHTML=time()});var _tmr=window._tmr||(window._tmr=[]);_tmr.push({id:"3211268",type:"pageView",start:(new Date).getTime()});
(function(a,d,b){if(!a.getElementById(b)){var c=a.createElement("script");c.type="text/javascript";c.async=!0;c.id=b;c.src="https://top-fwz1.mail.ru/js/code.js";b=function(){var b=a.getElementsByTagName("script")[0];b.parentNode.insertBefore(c,b)};"[object Opera]"==d.opera?a.addEventListener("DOMContentLoaded",b,!1):b()}})(document,window,"topmailru-code");var acc=document.getElementsByClassName("malloc-accordion"),i;
for(i=0;i<acc.length;i++)acc[i].addEventListener("click",function(){this.classList.toggle("active");var a=this.nextElementSibling;a.style.display="block"===a.style.display?"none":"block"});
